@startuml EER

hide empty members

class "EerEndpoint" as EerEndpoint <<MCSDEndpoint>>
class "EerMessagingOrganization" as EerOrganization <<MCSDOrganization>>
class "EerMessageDefinition" as EerMessageDefinition <<MessageDefinition>>
class "EerDeviceEUA" as EerDeviceEUA <<EerDevice>>
class "EerDeviceAP" as EerDeviceAP <<EerDevice>>
class "EerDeviceMSH" as EerDeviceMSH <<EerDevice>>

EerOrganization --> EerEndpoint : "has"
EerOrganization --> EerDeviceEUA : "uses"
EerDeviceAP --> EerOrganization : "acts as Endpoint for"
EerDeviceAP --> EerEndpoint : "instanciates"
EerDeviceEUA --> EerMessageDefinition : "supports"
EerEndpoint --> EerMessageDefinition : "sends"
EerEndpoint --> EerMessageDefinition : "receives"
EerDeviceMSH --> EerOrganization : "supports (potentially)"
EerDeviceMSH --> EerEndpoint : "supports (potentially)"

@enduml
