@startuml SMP

hide empty members

class "EerOrganization" as EerOrganization <<MCSDOrganization>>
class "EerEndpoint" as EerEndpoint <<MCSDEndpoint>>
class "EerMessageType" as EerMessageType <<EerMessageDefinition>>
class "SMP" as SMP <<eDeliveryMetadata>>

EerOrganization --> EerEndpoint : "has"
EerEndpoint --> EerMessageType : "receives"
EerOrganization --> SMP : "populates"
EerEndpoint --> SMP : "populates"
EerMessageType --> SMP : "populates"

@enduml
