#!/usr/bin/env bash

set -euo pipefail

VALIDATOR_JAR="${FHIR_VALIDATOR_JAR:-../validator_cli.jar}"
GENERATED_DIR="fsh-generated/resources"
PACKAGE_CACHE="${FHIR_PACKAGE_CACHE:-$HOME/.fhir/packages}"

CONTEXT_DIR="$(mktemp -d)"
trap 'rm -rf "$CONTEXT_DIR"' EXIT

sushi build --snapshot .

link_resources() {
  local source_dir="$1"
  local prefix="$2"

  if [[ ! -d "$source_dir" ]]; then
    echo "Missing validation dependency directory:"
    echo "  $source_dir"
    exit 1
  fi

  while IFS= read -r -d '' file; do
    ln -s \
      "$(realpath "$file")" \
      "$CONTEXT_DIR/${prefix}-$(basename "$file")"
  done < <(
    find "$source_dir" \
      -maxdepth 1 \
      -type f \
      -name '*.json' \
      ! -name 'package.json' \
      ! -name '.index.json' \
      ! -name 'ImplementationGuide-*.json' \
      -print0
  )
}

# Local resources generated by SUSHI.
link_resources "$GENERATED_DIR" "local"

# Exact package versions used by this SUSHI build.
#
# Start with packages that the log shows are actually required.
link_resources \
  "$PACKAGE_CACHE/ihe.iti.mcsd#3.9.0/package" \
  "mcsd-3.9.0"

link_resources \
  "$PACKAGE_CACHE/hl7.fhir.dk.core#3.4.0/package" \
  "dkcore-3.4.0"

link_resources \
  "$PACKAGE_CACHE/dk.ehmi.terminology#1.2.0/package" \
  "ehmi-term-1.2.0"

# Your generated snapshots contain definitions from this package.
link_resources \
  "$PACKAGE_CACHE/hl7.fhir.uv.extensions.r4#5.3.0/package" \
  "extensions-5.3.0"

mapfile -d '' FILES < <(
  find "$GENERATED_DIR" \
    -maxdepth 1 \
    -type f \
    -name '*.json' \
    ! -name 'ImplementationGuide-*.json' \
    -print0
)

java -jar "$VALIDATOR_JAR" \
  -version 4.0.1 \
  -tx n/a \
  -disable-default-resource-fetcher \
  -ig "$CONTEXT_DIR" \
  -output-style compact \
  "${FILES[@]}"run